Add insightsengineering/rtables.officer to Remotes (#293)
A solution for 
- https://github.com/insightsengineering/coredev-tasks/issues/600


# Overview

GRAN dev environment is failing
http://cedar.gene.com/gran/dev/SinglePkgLogs/teal.reporter.log because
`rtables.officer` is not released on GRAN. That's why, for the proper
`teal.reporter` installation you need to specify the path on GitHub so
`rtables.officer` gets installed from GitHub during regular package
installation.

```r
  pkg: teal.reporter ( Tue Dec 10 18:50:20 2024 ) -  	Existing temporary checkout found at this location. Updating
  pkg: teal.reporter ( Tue Dec 10 18:50:23 2024 ) -  	Temporary source directory successfully created: TRUE
  pkg: teal.reporter ( Tue Dec 10 18:58:44 2024 ) -  	Existing temporary checkout found at this location. Updating
  pkg: teal.reporter ( Tue Dec 10 18:58:45 2024 ) -  	Temporary source directory successfully created: TRUE
  pkg: teal.reporter ( Tue Dec 10 19:02:42 2024 ) -  	Package up to date at version 0.3.1.9018. Not rebuilding.
  ERROR  pkg: teal.reporter ( Tue Dec 10 19:20:15 2024 ) -  	Installation of teal.reporter from temporary repository failed
  ERROR  pkg: teal.reporter ( Tue Dec 10 19:20:15 2024 ) -  	Installation output:
		ERROR: dependency ‘rtables.officer’ is not available for package ‘teal.reporter’
		* removing ‘/mnt/gran_dir/GRANbuilds/dev/temp_lib/teal.reporter’
```


That's why we added `Remotes: insightsengineering/rtables.officer` in
`DESCRIPTION` file.

This issue also propagates to `teal` that can not be installed on GRAN
dev neither http://cedar.gene.com/gran/dev/SinglePkgLogs/teal.log

```r
  pkg: teal ( Wed Nov 20 02:49:43 2024 ) -  	Successfully checked out package source from https://gran:gldt-fDqzvirg_v-ivah2w4W-@code.roche.com/nest/insights-engineering/teal.git on branch main
  pkg: teal ( Wed Nov 20 02:49:43 2024 ) -  	Temporary source directory successfully created: TRUE
  pkg: teal ( Wed Nov 20 02:49:44 2024 ) -  	Had version 0.15.2.9088. Building new version 0.15.2.9089
  pkg: teal ( Wed Nov 20 02:49:45 2024 ) -  	Successfully built package.
  ERROR  pkg: teal ( Wed Nov 20 02:49:59 2024 ) -  	Package teal was not successfully installed and no output is available. Likely culprit: failure during installation of one of it's dependencies?
```

Signed-off-by: Marcin <133694481+m7pr@users.noreply.github.com>