Fix Integration tests (#443)
Fixes 

- https://github.com/insightsengineering/coredev-tasks/issues/673

One of the tests fail due to the old version of pandoc in the
non-validated environment.

```
  ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Failure ('test-render.R:179:5'): render() renders output based on metadata$output field:: - md_document containing markdown content, code chunks and their outputs ──
  `lines` (`actual`) not identical to c(...) (`expected`).
  
  `actual[1:5]`:   "test heading"   "============" "" "Lorem ipsum" ""
  `expected[1:4]`: "# test heading"                "" "Lorem ipsum" ""
  
  [ FAIL 1 | WARN 1 | SKIP 2 | PASS 366 ]
  Error: Test failures
  Execution halted
* DONE

```

Extended tests so they take care of the version of pandoc, which formats
headers differently based on the version.
Change in pandoc released in
https://pandoc.org/releases.html#pandoc-2.11.2-2020-11-19
also reported in 2020-10 in rmarkdown
https://github.com/rstudio/rmarkdown/issues/1956

---------

Signed-off-by: Marcin <133694481+m7pr@users.noreply.github.com>
Co-authored-by: github-actions <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: André Veríssimo <211358+averissimo@users.noreply.github.com>